apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
type: Opaque
data:
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: cGtfdGVzdF9kWEF0YzJWaGFHOXljbVV0T1RZdVkyeGxjbXN1WVdOamIzVnVkSE11WkdWMkpB  # base64 encoded
  CLERK_SECRET_KEY: c2tfdGVzdF9aUzNhVG9JRFFXVDVBd3FoQ1dmTTlsd1VFRzB3Z3Z1NU0zSWVwUUVSS0M=  # base64 encoded
  WEBHOOK_SECRET: eW91ci13ZWJob29rX3NlY3JldA==  # base64 encoded
  CLERK_ENCRYPTION_KEY: YXNkYWRhc2RhZGFzZGFzZGFzZGFzZA==  # base64 encoded