apiVersion: apps/v1
kind: Deployment
metadata:
  name: billbox-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billbox-frontend
  template:
    metadata:
      labels:
        app: billbox-frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/billbox-frontend:latest

# frontend/k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: billbox-frontend-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: billbox-frontend