apiVersion: apps/v1
kind: Deployment
metadata:
  name: billbox-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billbox-frontend
  template:
    metadata:
      labels:
        app: billbox-frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/PROJECT_ID/billbox-frontend:latest
